site_name: FAIMS 2.6 User and Module Documentation
theme: 
  name: readthedocs
  custom_dir: readthedocs
plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      toc_depth: 2
      permalink: True
